## 并行测试模块
```plantuml
@startuml

start

  :选择测试模式]
  
  :解析配置文件] 
  note right 
  1. datapath
  2. cmdvalue
  3. cmdexec
  4. cmdcon
  5. camerayaml
  6. info
  7. outpath
  end note
  
  :调用测试接口]
  
  :解析视频列表文件]
  
  partition Testing Process{
  :创建测试线程,
  执行ORB_SLAN2程序]
  repeat
  if (线程执行完成?) then (yes)
  :测试结果写入文件;
  else (no)
    if (线程执行超时？) then (yes)
    :结束线程]
    else (no)
    :sleep(1)]
    endif
  endif
  repeat while(1)
}
stop

@enduml
```

```plantuml

start

  :选择测试模式]
  
  :解析配置文件] 
  note right 
  1. datapath
  2. cmdvalue
  3. cmdexec
  4. cmdcon
  5. camerayaml
  6. info
  7. outpath
  end note
  
  :调用测试接口]
  
  :解析视频列表文件]
  
  partition Testing Process{
  :创建测试线程,
  执行ORB_SLAN2程序]
  #hotpink:while(1);
  if (线程执行完成?) then (yes)
  :测试结果写入文件]
  else (no)
    if (线程执行超时？) then (yes)
    :结束线程]
    else (no)
    :sleep(1)]
    #hotpink:goto while(1);
     detach
    endif
  endif
}
stop
@enduml
```







## 评估模块
```plantuml
@startuml

  start
  split
  :读取VM和VSLAM模式
   的位姿文件]
  :绘制位姿结果图]
  :保存图像到不同数
   据集的目录下]
  split again
  :读取位姿文件]
  :计算vm模式与VSLAM
   模式之间的误差]
  :保存误差结果到csv
  文件]
  :绘制误差结果图]
  end split
  :读取csv文件]
  :将结果图汇总到
   html文件]
stop

@enduml
```
## 评估模块
```plantuml
@startuml
  |#lightblue|l|plotfig
  |#AntiqueWhite|c|gethtml
  |#lightgreen|r|errorAnalysis
  
  |c|
  start
  split
  |l|
  :读取VM和VSLAM模式
   的位姿文件]
  :绘制位姿结果图]
  :保存图像到不同数
   据集的目录下]
  |r|
  split again
  :读取位姿文件]
  :计算vm模式与VSLAM
   模式之间的误差]
  :保存误差结果到csv
  文件]
  :绘制误差结果图]
  end split
  
  |c|
  :读取csv文件]
  :将结果图汇总到
   html文件]
stop

@enduml
```

### erroranalysis
```plantuml
@startuml

title Empty Diagram
start
  : 1. 根据VM位姿提取直
    线行驶路段]
    
  : 2. 计算VSLAM与VM在
    直线行驶路段的位置
    距离和角度差异]
    
  : 3. 统计距离误差超
    过阈值的直线路段数
    量]
    
  : 4. 统计VM和VSLAM的
    总里程]
    
  : 5. 计算起始点距离]
  
  : 6. 保存结果]
  
  : 7. 绘制2中计算的距
    离和角度差异]
end
@enduml
```


## Demo

```plantuml
@startuml
title Point two queries to same activity\nwith `goto`
start
if (Test Question?) then (yes)
'space label only for alignment
label sp_lab0
label sp_lab1
'real label
label lab
:shared;
else (no)
if (Second Test Question?) then (yes)
label sp_lab2
goto sp_lab1
else
:nonShared;
endif
endif
:merge;
@enduml
```